title: "Gerald Akorli & Uduak Essien"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
google_analytics: "UA-XXXXXXXX-X"
baseurl: "/" 
url: "/" 
twitter_username: 
github_username:  bravoclassic

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
# resume link
resume: 